### ISSUE TITLE
Same files

### ISSUE THREAD

**Issue by hrishikeshAvatron** [Deagek/tableview#1]
Content in TableView.py and and TableView_test.py are same.

**Comment by Deagek** [comment]
Thanks for pointing that out.

 

Updated.

 

From: hrishikeshAvatron ***@***.***> 
Sent: Thursday, 19 October 2023 6:43 PM
To: Deagek/tableview ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Deagek/tableview] Same files (Issue #1)

 

Content in TableView.py and and TableView_test.py are same.

**Comment by Deagek** [comment]
Issue closed.
